/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import Model.Cliente;
import Model.Servico;
import javax.swing.JComboBox;
import javax.swing.JTable;

public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    public Agenda() {
        initComponents();
        controller = new AgendaController(this);

        controller.atualizaTabela();
        controller.atualizaCliente();
        controller.atualizaServico();

        jToggleButtonAgendar.addActionListener(evt -> adicionarNaTabela());

        
        jComboBoxCampoServico.addActionListener(evt -> controller.atualizaValor());
    }

    private void adicionarNaTabela() {
        String id = jTextFieldId.getText();

        Cliente clienteSelecionado = (Cliente) jComboBoxCampoCliente.getSelectedItem();
        String cliente = clienteSelecionado != null ? clienteSelecionado.getNome() : "";

        Servico servicoSelecionado = (Servico) jComboBoxCampoServico.getSelectedItem();
        String servico = servicoSelecionado != null ? servicoSelecionado.getDescricao() : "";

        String valor = jTextFieldCampoValor.getText();
        String data = jTextFieldCampoData.getText();
        String hora = jTextFieldCampoHora.getText();
        String observacao = "";

        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTableAgendamentos.getModel();

        modelo.addRow(new Object[]{id, cliente, servico, valor, data, hora, observacao});

        jTextFieldId.setText("");
        jTextFieldCampoValor.setText("");
        jTextFieldCampoData.setText("");
        jTextFieldCampoHora.setText("");
        jComboBoxCampoCliente.setSelectedIndex(0);
        jComboBoxCampoServico.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButtonAgendar = new javax.swing.JToggleButton();
        jTextFieldCampoHora = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldCampoValor = new javax.swing.JTextField();
        jTextFieldCampoData = new javax.swing.JTextField();
        jComboBoxCampoCliente = new javax.swing.JComboBox();
        jComboBoxCampoServico = new javax.swing.JComboBox();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTableAgendamentos = new javax.swing.JTable();
        jLabelTabelaPreco = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelAgenda = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelServico = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jLabelFundoAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/TabelaValor_resized.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 570, 440));

        jToggleButtonAgendar.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButtonAgendar.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jToggleButtonAgendar.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButtonAgendar.setText("Agendar");
        getContentPane().add(jToggleButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 565, 400, 60));

        jTextFieldCampoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 390, 50));

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 390, 50));

        jTextFieldCampoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 390, 50));

        jTextFieldCampoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 390, 50));

        jComboBoxCampoCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCampoClienteItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxCampoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 390, 50));

        jComboBoxCampoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCampoServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCampoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 390, 50));

        jTableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPaneTabela.setViewportView(jTableAgendamentos);

        getContentPane().add(jScrollPaneTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 1050, 240));

        jLabelTabelaPreco.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTabelaPreco.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelTabelaPreco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTabelaPreco.setText("Tabela de Preços");
        getContentPane().add(jLabelTabelaPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, -1, -1));

        jLabelValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelValor.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor:");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jLabelAgenda.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAgenda.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabelAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgenda.setText("Agenda");
        getContentPane().add(jLabelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, -1));

        jLabelId.setBackground(new java.awt.Color(255, 255, 255));
        jLabelId.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("Id:");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabelCliente.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente:");
        getContentPane().add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabelHora.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHora.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora:");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));

        jLabelData.setBackground(new java.awt.Color(255, 255, 255));
        jLabelData.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data:");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        jLabelServico.setBackground(new java.awt.Color(255, 255, 255));
        jLabelServico.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("Servico:");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Fundo2.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 1150, 890));

        jLabelFundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/FundoAgenda.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 1450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCampoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoHoraActionPerformed

    private void jTextFieldCampoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoValorActionPerformed

    private void jTextFieldCampoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoDataActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jComboBoxCampoClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCampoClienteItemStateChanged
    this.controller.atualizaValor();
    }//GEN-LAST:event_jComboBoxCampoClienteItemStateChanged

    private void jComboBoxCampoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCampoServicoActionPerformed
        
    }//GEN-LAST:event_jComboBoxCampoServicoActionPerformed
 
     private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
    }
     

public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Agenda().setVisible(true);
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCampoCliente;
    private javax.swing.JComboBox jComboBoxCampoServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundoAgenda;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelTabelaPreco;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTableAgendamentos;
    private javax.swing.JTextField jTextFieldCampoData;
    private javax.swing.JTextField jTextFieldCampoHora;
    private javax.swing.JTextField jTextFieldCampoValor;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JToggleButton jToggleButtonAgendar;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableAgendamentos() {
    return jTableAgendamentos;
}

public void setjTableAgendamentos(JTable jTableAgendamentos) {
    this.jTableAgendamentos = jTableAgendamentos;
}

public JComboBox<Cliente> getjComboBoxCampoCliente() {
    return jComboBoxCampoCliente;
}

public void setjComboBoxCampoCliente(JComboBox<Cliente> jComboBoxCampoCliente) {
    this.jComboBoxCampoCliente = jComboBoxCampoCliente;
}

public JComboBox<Servico> getjComboBoxCampoServico() {
    return jComboBoxCampoServico;
}

public void setjComboBoxCampoServico(JComboBox<Servico> jComboBoxCampoServico) {
    this.jComboBoxCampoServico = jComboBoxCampoServico;
}

public javax.swing.JTextField getjTextFieldCampoValor() {
    return jTextFieldCampoValor;
}
}